AZP 2.5-2

diff --git a/usr/bin/azp b/usr/bin/azp
--- a/usr/bin/azp
+++ b/usr/bin/azp
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-### AZP Paket Sistemi 2.5
+### AZP Paket Sistemi 2.5-2
 # AZP Offical Site: https://azp-paket-sistemi.github.io
 # AZP Offical Depo: https://azp-paket-sistemi.github.io/azp-depo
 
@@ -28,30 +28,13 @@ then
 fi
 
 # Bağımlılıqları yoxlama
-depends1="zip"
-depends2="unzip"
-depends3="wget"
-depends4="tar"
-if ! which $depends1 &> /dev/null;
-then
-  echo "$error" "$depends1" $" -- not installed !"
-  exit
-fi
-if ! which $depends2 &> /dev/null;
-then
-  echo "$error" "$depends2" $" -- not installed !"
-  exit
-fi
-if ! which $depends3 &> /dev/null;
-then
-  echo "$error" "$depends3" $" -- not installed !"
-  exit
-fi
-if ! which $depends4 &> /dev/null;
-then
-  echo "$error" "$depends4" $" -- not installed !"
-  exit
-fi
+depends=("zip" "unzip" "wget" "tar" "ping")
+for i in ${depends}; do
+  if ! command -v "${i}" &>/dev/null; then
+    echo "$error" "${i}" $" -- not installed !"
+    exit
+  fi
+done
 
 # Köhnə data yoxlama
 if [ -d /tmp/azptmp ]
@@ -181,7 +164,7 @@ then
        / ____ \  / /__| |     
       /_/    \_\/_____|_|     
                                
-                 2.5   
+                 2.5-2   
    
   """
 
@@ -209,7 +192,7 @@ mkdir -p /var/cache/azp-archives &>/dev/null
 
 if ! [ -f /etc/azp-version ]
 then
-  echo "2.5" >> /etc/azp-version
+  echo "2.5-2" >> /etc/azp-version
 fi
 
 # Paket quraşdırma
@@ -306,21 +289,21 @@ then
     rm -r /tmp/azptmp &>/dev/null
     exit
   fi
-  if [ -d /var/cache/azp/$i_program ]
+  if [ -d /var/cache/azp/applications/$i_program ]
   then
     echo "$process" $"This program is already installed, will be replaced with a new one ..."
-    /var/cache/azp/$(cat app-name)/azprm &>/dev/null
+    /var/cache/azp/applications/$(cat app-name)/azprm &>/dev/null
   fi
-  mkdir -p /var/cache/azp/$i_program
-  cp -r info /var/cache/azp/$i_program
-  cp -r app-name /var/cache/azp/$i_program
-  cp -r files /var/cache/azp/$i_program
-  echo '#!/bin/bash' >> /var/cache/azp/$i_program/azprm
-  echo 'fayllar=$(cat files)' >> /var/cache/azp/$i_program/azprm
-  echo 'rm -rf $fayllar' >> /var/cache/azp/$i_program/azprm
-  echo 'i_program=$(cat app-name)' >> /var/cache/azp/$i_program/azprm
-  echo 'rm -rf /var/cache/azp/$i_program' >> /var/cache/azp/$i_program/azprm
-  chmod u+x /var/cache/azp/$i_program/azprm
+  mkdir -p /var/cache/azp/applications/$i_program
+  cp -r info /var/cache/azp/applications/$i_program
+  cp -r app-name /var/cache/azp/applications/$i_program
+  cp -r files /var/cache/azp/applications/$i_program
+  echo '#!/bin/bash' >> /var/cache/azp/applications/$i_program/azprm
+  echo 'fayllar=$(cat files)' >> /var/cache/azp/applications/$i_program/azprm
+  echo 'rm -rf $fayllar' >> /var/cache/azp/applications/$i_program/azprm
+  echo 'i_program=$(cat app-name)' >> /var/cache/azp/applications/$i_program/azprm
+  echo 'rm -rf /var/cache/azp/applications/$i_program' >> /var/cache/azp/applications/$i_program/azprm
+  chmod u+x /var/cache/azp/applications/$i_program/azprm
   mkdir azpsrc
   if ! tar -xf src.tar.bz2 -C azpsrc;
   then
@@ -331,17 +314,45 @@ then
     echo "$process" $"Files copied to file system..."
   fi
   sleep 1
+  echo "$(tar -tf src.tar.bz2)" >> azpsrc/srcfilelist
   cd azpsrc
-  cp -prf * /
+  # Qısayol yoxlama
+  if [[ -d /tmp/azptmp/azpsrc/lib ]]
+  then
+    if [[ -L /lib ]]
+    then
+      cd /tmp/azptmp/azpsrc/lib
+      cp -prf * /lib
+      cd ..
+      rm -r /tmp/azptmp/azpsrc/lib
+    fi
+  fi
+  # Düzgün kopyalama prosesi
+  echo "$process" $"Create files list..."
+  for list in $(cat srcfilelist);
+  do
+    if [ -f ${list} ]
+    then
+      echo "${list}" >> copyfilelist
+    else
+      echo "${list}" >> folderslist
+    fi
+  done
+  echo "$process" $"Create folders list..."
+  for folders in $(cat folderslist);
+  do
+    if [ ! -s /${folders} ]
+    then
+      mkdir -p /${folders}
+    fi
+  done
+  echo "$process" $"Files copied to file system..."
+  for cplist in $(cat copyfilelist);
+  do
+    cp -prf ${cplist} /${cplist}
+  done
   cd ..
-  echo "$(tar -tf src.tar.bz2)" >> srcfilelist
-  cp srcfilelist /
-  cd /
-  chown root $(cat srcfilelist)
-  cd /tmp/azptmp
-  cd ..
-  rm -r azptmp
-  rm -r /srcfilelist
+  rm -r /tmp/azptmp
   echo "$finished" $"Installation is complete"
 fi
 
@@ -359,13 +370,13 @@ then
   read -p "Remove application ? [h/y]: " program_r_secim
   if [[ $program_r_secim == "h" ]]
   then
-    cd /var/cache/azp/ &>/dev/null
+    cd /var/cache/azp/applications/ &>/dev/null
     if ! cd $r_program &>/dev/null;
     then
       echo "$error" $"There is no such program !"
       exit
     fi
-    /var/cache/azp/$r_program/azprm &>/dev/null
+    /var/cache/azp/applications/$r_program/azprm &>/dev/null
     sleep 1
     echo "$finished" $"Process Finished"
     cd ..
@@ -388,21 +399,21 @@ then
     echo "$error" $"The program was not selected !"
     exit
   fi
-  if ! [[ -d /var/cache/azp/$program_info ]]
+  if ! [[ -d /var/cache/azp/applications/$program_info ]]
   then
     echo "$error" $"Application not found !"
     exit
   fi
   echo "-------------------"
-  if ! [[ -f /var/cache/azp/$program_info/info ]]
+  if ! [[ -f /var/cache/azp/applications/$program_info/info ]]
   then
     echo "$error" $"'info' file not found !"
     exit
   fi
-  name=$(sed -n 1p /var/cache/azp/$program_info/info)
-  description=$(sed -n 2p /var/cache/azp/$program_info/info)
-  version=$(sed -n 3p /var/cache/azp/$program_info/info)
-  maintainer=$(sed -n 4p /var/cache/azp/$program_info/info)
+  name=$(sed -n 1p /var/cache/azp/applications/$program_info/info)
+  description=$(sed -n 2p /var/cache/azp/applications/$program_info/info)
+  version=$(sed -n 3p /var/cache/azp/applications/$program_info/info)
+  maintainer=$(sed -n 4p /var/cache/azp/applications/$program_info/info)
   echo -e "\033[1;32m name: \033[:0m" "\033[1;37m${name:6}\033[:0m"
   echo -e "\033[1;32m description: \033[:0m" "\033[1;37m${description:13}\033[:0m"
   echo -e "\033[1;32m version: \033[:0m" "\033[1;37m${version:8}\033[:0m"
@@ -414,7 +425,7 @@ fi
 # Quraşdırılan programlar listəsi
 if [[ $1 == "-pl" ]]
 then
-  cd /var/cache/azp &>/dev/null
+  cd /var/cache/azp/applications &>/dev/null
   echo $"Apps:"
   echo -e "\033[1;33m $(ls) \033[:0m"
   cd ..
@@ -551,43 +562,68 @@ then
     rm -r /tmp/azptmp &>/dev/null
     exit
   fi
-  if [ -d /var/cache/azp/$i_program ]
+  if [ -d /var/cache/azp/applications/$i_program ]
   then
     echo "$warning" $"This program is already installed, will be replaced with a new one ..."
-    chattr -i /var/cache/azp/$i_program
-    /var/cache/azp/$(cat app-name)/azprm &>/dev/null
+    /var/cache/azp/applications/$(cat app-name)/azprm &>/dev/null
   fi
-  mkdir -p /var/cache/azp/$i_program
-  cp -r info /var/cache/azp/$i_program
-  cp -r app-name /var/cache/azp/$i_program
-  cp -r files /var/cache/azp/$i_program
-  echo '#!/bin/bash' >> /var/cache/azp/$i_program/azprm
-  echo 'fayllar=$(cat files)' >> /var/cache/azp/$i_program/azprm
-  echo 'rm -rf $fayllar' >> /var/cache/azp/$i_program/azprm
-  echo 'i_program=$(cat app-name)' >> /var/cache/azp/$i_program/azprm
-  echo 'rm -rf /var/cache/azp/$i_program' >> /var/cache/azp/$i_program/azprm
-  chmod u+x /var/cache/azp/$i_program/azprm
+  mkdir -p /var/cache/azp/applications/$i_program
+  cp -r info /var/cache/azp/applications/$i_program
+  cp -r app-name /var/cache/azp/applications/$i_program
+  cp -r files /var/cache/azp/applications/$i_program
+  echo '#!/bin/bash' >> /var/cache/azp/applications/$i_program/azprm
+  echo 'fayllar=$(cat files)' >> /var/cache/azp/applications/$i_program/azprm
+  echo 'rm -rf $fayllar' >> /var/cache/azp/applications/$i_program/azprm
+  echo 'i_program=$(cat app-name)' >> /var/cache/azp/applications/$i_program/azprm
+  echo 'rm -rf /var/cache/azp/applications/$i_program' >> /var/cache/azp/applications/$i_program/azprm
+  chmod u+x /var/cache/azp/applications/$i_program/azprm
   mkdir azpsrc
   if ! tar -xf src.tar.bz2 -C azpsrc;
   then
     echo "$error" $"There was a problem with the 'src' file !"
     rm -r /tmp/azptmp &>/dev/null
     exit
-  else
-    echo "$process" $"Files copied to file system..."
   fi
   sleep 1
+  echo "$(tar -tf src.tar.bz2)" >> azpsrc/srcfilelist
   cd azpsrc
-  cp -prf * /
+  # Qısayol yoxlama
+  if [[ -d /tmp/azptmp/azpsrc/lib ]]
+  then
+    if [[ -L /lib ]]
+    then
+      cd /tmp/azptmp/azpsrc/lib
+      cp -prf * /lib
+      cd ..
+      rm -r /tmp/azptmp/azpsrc/lib
+    fi
+  fi
+  # Düzgün kopyalama prosesi
+  echo "$process" $"Create files list..."
+  for list in $(cat srcfilelist);
+  do
+    if [ -f ${list} ]
+    then
+      echo "${list}" >> copyfilelist
+    else
+      echo "${list}" >> folderslist
+    fi
+  done
+  echo "$process" $"Create folders list..."
+  for folders in $(cat folderslist);
+  do
+    if [ ! -s /${folders} ]
+    then
+      mkdir -p /${folders}
+    fi
+  done
+  echo "$process" $"Files copied to file system..."
+  for cplist in $(cat copyfilelist);
+  do
+    cp -prf ${cplist} /${cplist}
+  done
   cd ..
-  echo "$(tar -tf src.tar.bz2)" >> srcfilelist
-  cp srcfilelist /
-  cd /
-  chown root $(cat srcfilelist)
-  cd /tmp/azptmp
-  cd ..
-  rm -r azptmp
-  rm -r /srcfilelist
+  rm -r /tmp/azptmp
   echo "$finished" $"Process Finished"
   cd ..
   rm -r /tmp/azp-depoins &>/dev/null
