AZP 3.5

diff --git a/usr/bin/azp-depends b/usr/bin/azp-depends
--- a/usr/bin/azp-depends
+++ b/usr/bin/azp-depends
@@ -1,16 +1,16 @@
 #!/bin/bash
 
-### AZP Paket Sistemi 3.0-1
+### AZP Paket Sistemi 3.5
 # AZP Offical Site: https://azp-paket-sistemi.github.io
 # AZP Offical Depo: https://azp-paket-sistemi.github.io/azp-depo
 
 # © 2021-2022 AZP
-# © 2019-2022 PacPERRO OS
+# © 2019-2022 PacPERRO
 
 TEXTDOMAINDIR=/usr/share/locale
 TEXTDOMAIN=azp-depends
 
-# Bəzi teglər :)
+# Rənglər
 error=$(echo -e "\033[1;31m E: \033[:0m")
 process=$(echo -e "\033[1;34m P: \033[:0m")
 finished=$(echo -e "\033[1;32m F: \033[:0m")
@@ -18,10 +18,13 @@ remove=$(echo -e "\033[1;31m R: \033[:0m")
 info=$(echo -e "\033[1;37m I: \033[:0m")
 warning=$(echo -e "\033[1;33m V: \033[:0m")
 
+# Prosesor arxitekturası
+arch=$(uname -m)
+
 azp_pack_depo=$(cat /etc/azp/azp-depo/depo)
 if [ $1 == "depends" ]
 then
-  [[ -d /tmp/azp-depends ]] && rm -r /tmp/azp-depends
+  [[ -d /tmp/azp-depends ]] && rm -r /tmp/azp-depends &>/dev/null
   [[ ! -d /tmp/azp-depends ]] && mkdir -p /tmp/azp-depends
     for depends in $2;
     do
@@ -32,9 +35,20 @@ then
       if ! wget $azp_pack_depo/${depends:0:1}/${depends}/latest-file &>/dev/null;
       then
         echo "$error" "${depends}" $" == depends not found !"
+        rm -r /tmp/azp-depends &>/dev/null
         exit
       fi
-      pack=$(cat latest-file)
+      latestf=$(cat latest-file)
+      if [ -z $latestf ]
+      then
+        if ! wget $azp_pack_depo/${depends:0:1}/${depends}/latest-file_$arch &>/dev/null;
+          then
+          echo -e "$error" $"Depo not connect !"
+          rm -r /tmp/azp-depoins &>/dev/null
+          exit
+        fi
+      fi
+      pack=$([[ -z $(cat latest-file) ]] && echo "$(cat latest-file_$arch)" || echo "$(cat latest-file)")
       echo "$process" "$pack --" $"Download depends..."
       wget $azp_pack_depo/${depends:0:1}/${depends}/$pack &>/dev/null
       if [ ! -f $pack ]
@@ -42,6 +56,7 @@ then
         echo "$error" $"Package Not Found !"
         exit
       fi
+      cp -r $pack /var/cache/azp-archives
       if ! unzip $pack -d /tmp/azp-depends/${depends}/azptmp &>/dev/null;
       then
         echo "$error" $"The package could not be broken !"
@@ -49,6 +64,9 @@ then
       else
         echo "$process" $"Files Extract..."
       fi
+      # AZP Archives faylını yeniləmə
+      cp -r $pack /var/cache/azp-archives
+      echo "$pack -- $(date "+DATE: %D   TIME: %T")" >> /var/cache/azp-archives/archives
       cd /tmp/azp-depends/${depends}/azptmp
       i_program=$(cat app-name)
       info=$(sed -n 1p info)
@@ -75,12 +93,14 @@ then
         fi
         if [[ ${line_description:14} == "*" ]]
         then
-           line_description_ct=$(sed -n 5p info)
-           if [[ ${line_description_ct:0:12} != "descritpion:" ]]
-           then
-             echo "$error" $"'description:' not spelled correctly in 'info' file! !"
-             exit
-           fi
+           for ds in $(grep -n "description:" info);
+           do
+             if ! [[ ${ds:0:1} -gt 2 ]]
+             then
+                echo "$error" $"'description:' not spelled correctly in 'info' file! !"
+                exit
+             fi
+           done
         fi
         line_version=$(sed -n 3p info)
         if [[ ${line_version:0:8} != "version:" ]]
@@ -115,6 +135,17 @@ then
         echo "$error" $"'src.tar.bz2' not found, package invalid"
         rm -r /tmp/azp-depends/${depends}/azptmp &>/dev/null
         exit
+      fi
+      # arch kontrol
+      line_arch=$(sed -n 5p info)
+      if [[ ${line_arch:0:13} == "architecture:" ]]
+      then
+        if [[ ${line_arch:14} != ${arch} ]] && [[ ${line_arch:14} != "amd64" ]]
+        then
+          echo "$error" $"Software arch is incompatible with processor arch"
+          echo $"Processor Arch: " "${arch}"
+          echo $"Program Arch: " "${line_arch:6}"
+        fi
       fi
       # Paket bağımlılıqları quraşdırma
       if [ -f depends ]
@@ -171,7 +202,7 @@ then
       echo "$finished" $"Installation is complete for depends"
      else
       info_version=$(sed -n 3p /var/cache/azp/applications/${depends}/info)
-      echo "$warning" "${depends} -- " $"Depends installed" "(${info_version:8})"
+      echo "$warning" "${depends} -- " $"Depends installed" "(${info_version:9})"
      fi
     done
 fi
@@ -183,4 +214,14 @@ then
     azp-depends depends ${adl}
   done
 fi
-rm -r /tmp/azp-depends
+[[ -f /tmp/azp-depends ]] && rm -r /tmp/azp-depends
+
+if [ $1 == "dependsr" ]
+then
+  rm_depends=$2
+  echo "$process" "$rm_depends" $"== remove depends..."
+  d_fayllar=$(cat /var/cache/azp/applications/$rm_depends/files)
+  rm -rf $d_fayllar &>/dev/null
+  rm_d=$(cat /var/cache/azp/applications/$rm_depends/app-name)
+  rm -rf /var/cache/azp/applications/$rm_d &>/dev/null
+fi
